# Generated by Django 4.0.6 on 2022-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_is_ended_auction_is_finished_and_more'),
        ('accounts', '0002_company_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, to='auctions.service'),
        ),
    ]
