# Generated by Django 4.0.5 on 2022-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(to='auctions.service'),
        ),
    ]
