# Generated by Django 4.0.5 on 2022-06-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost', models.PositiveSmallIntegerField()),
                ('customers', models.ManyToManyField(related_name='companies', to='accounts.account')),
            ],
        ),
    ]
