# Generated by Django 4.0.5 on 2022-06-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='service',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='company',
            name='customers',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(choices=[('MSK', 'Москва'), ('SPB', 'Санкт-Петербург'), ('YAR', 'Ярославль')], default='MSK', max_length=3),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
