# Generated by Django 4.0.5 on 2022-06-03 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_remove_account_service_remove_company_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_service', models.PositiveSmallIntegerField(choices=[(1, 'Замена резины'), (2, 'Замена масла'), (3, 'Замена свечей'), (4, 'Химчистка'), (5, 'Чистка воздуховодов'), (6, 'Полная диагностика'), (7, 'Регулировка развала-схождения'), (8, 'Мойка')], default=6)),
                ('is_finished', models.BooleanField(default=False)),
                ('timer_start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('release_year', models.CharField(max_length=4)),
                ('model', models.CharField(max_length=128)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='auction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.car'),
        ),
        migrations.AddField(
            model_name='service',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.car'),
            preserve_default=False,
        ),
    ]
