# Generated by Django 4.0.5 on 2022-06-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auction_car_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='service',
            name='car',
        ),
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ремонт'), (2, 'Обслуживание')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='chosen_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.service'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.auction')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
