# Generated by Django 4.0.5 on 2022-06-16 23:48

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='is_finished',
            new_name='is_company_chosen',
        ),
        migrations.AddField(
            model_name='auction',
            name='timer_end',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='order',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
