# Generated by Django 4.0.5 on 2022-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_timer_end_auction_datetime_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_started',
            new_name='datetime_start',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
