# Generated by Django 4.0.5 on 2022-06-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_date_started_order_datetime_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
