# Generated by Django 4.0.5 on 2022-06-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_order_company_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='is_company_chosen',
            new_name='is_ended',
        ),
        migrations.RemoveField(
            model_name='order',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='datetime_end',
        ),
    ]
