# Generated by Django 4.0.5 on 2022-06-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_city_offer'),
        ('accounts', '0012_rename_is_company_chosen_auction_is_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.offer'),
            preserve_default=False,
        ),
    ]
