# Generated by Django 4.0.5 on 2022-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(choices=[('MSK', 'Москва'), ('SPB', 'Санкт-Петербург'), ('YAR', 'Ярославль')], default='MSK', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
