# Generated by Django 4.0.5 on 2022-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_choice',
            field=models.PositiveSmallIntegerField(choices=[(10, '10 minutes'), (60, '1 hour'), (1440, '1 day')], default=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
