# Generated by Django 4.0.5 on 2022-07-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
