# Generated by Django 4.0.5 on 2022-07-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_offer_is_chosen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='offer',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
    ]
