# Generated by Django 4.0.5 on 2022-07-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_offer_unique_together_remove_offer_auction_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.offer'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
